# Setup
title:               Genussklinik
tagline:             '[Not] Just another Github site.'
description:         'Description.'
url:                 https://genussklinik.github.io
baseurl:             '/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Genuss Klinik
  url:               https://genussklinik.de
  email:             kontakt@genussklinik.de

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
