# Setup
title:               Genussklinik
tagline:             '[Not] Just another Github site.'
description:         '<a href="https://www.xup.in/dl,42112980/GK_Logo.png/" target="_blank"><img src="https://www1.xup.in/exec/ximg.php?fid=42112980" border="0"></a>'
url:                 https://genussklinik.github.io
baseurl:             '/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Genuss Klinik
  url:               https://genussklinik.de
  email:             kontakt@genussklinik.de

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
